# Generated by Django 6.0.2 on 2026-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=35)),
                ('pet_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('HORSE', 'Horse'), ('COW', 'Cow'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('PIG', 'Pig'), ('FARM_ANIMAL', 'Farm Animal'), ('HOUSE_ANIMAL', 'House Animal'), ('AQUATIC_ANIMAL', 'Aquatic Animal'), ('EXOTIC', 'Exotic')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
