# Generated by Django 6.0.2 on 2026-02-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('HORSE', 'Horse'), ('COW', 'Cow'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('PIG', 'Pig'), ('FARM_ANIMAL', 'Farm Animal'), ('HOUSE_ANIMAL', 'House Animal'), ('AQUATIC_ANIMAL', 'Aquatic Animal'), ('EXOTIC', 'Exotic')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('number_of_aplications', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('veterinarian_name', models.CharField(blank=True, max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pet.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vaccine.vaccine')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('pet', 'vaccine', 'application_date')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccines',
            field=models.ManyToManyField(blank=True, related_name='pets', through='pet.PetVaccination', to='vaccine.vaccine'),
        ),
    ]
