# Generated by Django 6.0.2 on 2026-02-14 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('number_of_aplications', models.PositiveIntegerField(default=1)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('veterinarian_name', models.CharField(blank=True, max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pet.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vaccine.vaccine')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('pet', 'vaccine', 'application_date')},
            },
        ),
    ]
