# Generated by Django 6.0.2 on 2026-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_petvaccination'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccines',
            field=models.ManyToManyField(blank=True, related_name='pets', through='pet.PetVaccination', to='vaccine.vaccine'),
        ),
    ]
