# Generated by Django 6.0.2 on 2026-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_vaccines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petvaccination',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
