# Generated by Django 6.0.2 on 2026-02-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_petvaccination_application_date'),
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petvaccination',
            unique_together={('pet', 'vaccine')},
        ),
    ]
